load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_binary")

# https://bazelbuild.github.io/rules_kotlin/kotlin

kt_jvm_binary(
    name = "hello",
    srcs = ["hello.kt"],
    main_class = "HelloKt",
)

kt_jvm_binary(
    name = "max",
    srcs = ["max.kt"],
    main_class = "MaxKt",
)
